export const labels = {
  appName: 'TrustMe Admin',
  login: 'Log in',
  logout: 'Log out',
  username: 'Username',
  password: 'Password',
  overview: 'Overview',
  settings: 'Settings',
  apiKeys: 'API keys',
  createApiKey: 'Create API key',
  apiKeyName: 'Name',
  apiKeyScopes: 'Scopes',
  apiKeyCreated: 'Created',
  apiKeyExpires: 'Expires',
  apiKeyLastUsed: 'Last used',
  apiKeyStatus: 'Status',
  apiKeyPrefix: 'Key prefix',
  apiKeyActive: 'Active',
  apiKeyRevoked: 'Revoked',
  apiKeyExpired: 'Expired',
  apiKeyRevoke: 'Revoke',
  apiKeyRevokeConfirm: 'Revoke this API key?',
  apiKeyOneTimeWarning: 'Copy this key now. It will not be shown again.',
  apiKeyRawKey: 'API key',
  apiKeyRawSecret: 'HMAC secret',
  apiKeyPartnerBarcode: 'Partner treasury barcode',
  apiKeyPartnerBarcodeDescription: 'Required for partner scopes. The linked member must be a real (non-demo) account.',
  apiKeyPartnerBuyers: 'Create and read temporary buyers.',
  apiKeyPartnerDeposits: 'Verify and credit partner USDT deposits.',
  apiKeyPartnerCheckout: 'Initiate and settle partner checkouts.',
  apiKeyCreatedSuccess: 'API key created.',
  apiKeyRevokedSuccess: 'API key revoked.',
  apiKeyNameDescription: 'A descriptive name for the child platform.',
  apiKeyMarketAverage: 'Read the network commission average.',
  apiKeyReserves: 'Read public reserve and solvency figures.',
  apiKeyExecuteTransfer: 'Execute a transfer on behalf of a member (future scope).',
  apiKeyOptionalExpiry: 'Optional expiry',
  apiKeyBack: 'Back to API keys',
  withdrawals: 'Withdrawals',
  identityReviews: 'Identity reviews',
  ledger: 'Ledger',
  vaultUsdt: 'Vault USDT',
  couponsInCirculation: 'Coupons in circulation',
  demoData: 'Demo / test data',
  demoCouponsInCirculation: 'Demo coupons in circulation',
  demoUsers: 'Demo users',
  feesCollected: 'Fees collected',
  withdrawalPending: 'Withdrawal pending',
  dust: 'Member dust',
  commissionNetworkAverage: 'Network commission average',
  solvencySurplus: 'Solvency surplus',
  custody: 'Custody',
  obligations: 'Obligations',
  solvent: 'Solvent',
  insolvent: 'Insolvent',
  unavailable: 'unavailable',
  available: 'available',
  chain: 'Chain status',
  hotWallet: 'Hot wallet',
  headBlock: 'RPC head block',
  nextBlock: 'Next scan block',
  lag: 'Block lag',
  usdt: 'USDT',
  nativeBalance: 'Native balance (wei)',
  transactions24h: 'Transactions in the last 24 hours',
  transactionType: 'Transaction type',
  count: 'Count',
  withdrawalBaseFeeBps: 'Withdrawal base fee (bps; 20 bps = 0.2%)',
  minimumFeeMicroUsdt: 'Minimum withdrawal fee (USDT)',
  minimumWithdrawalMicroUsdt: 'Minimum withdrawal (USDT)',
  autoApprovalLimitMicroUsdt: 'Auto-approval limit (USDT)',
  requireIdentityForWithdrawal: 'Require identity verification for withdrawals',
  identityRequiredBeforeSpending: 'Require verified identity before spending',
  feeEquivalent: 'bps =',
  save: 'Save settings',
  barcode: 'Member barcode',
  country: 'Country',
  identityVerificationStatus: 'Identity verification',
  grossCoupons: 'Gross coupons',
  fee: 'Fee',
  net: 'Net',
  destination: 'Destination',
  status: 'Status',
  chainTxHash: 'Chain transaction',
  createdAt: 'Created',
  actions: 'Actions',
  broadcastedAt: 'Broadcasted',
  approve: 'Approve',
  reject: 'Reject',
  filter: 'Filter',
  allStatuses: 'All statuses',
  allTypes: 'All transaction types',
  previous: 'Previous',
  next: 'Next',
  externalReference: 'External reference',
  coupons: 'Coupons',
  search: 'Search',
  from: 'From',
  to: 'To',
  entries: 'Entries',
  success: 'Success',
  error: 'Error',
  saved: 'Settings saved.',
  approved: 'Withdrawal approved and queued.',
  rejected: 'Withdrawal rejected and refunded.',
  identityReviewApproved: 'Identity review approved.',
  identityReviewRejected: 'Identity review rejected.',
  submittedAt: 'Submitted',
  decidedAt: 'Decided',
  document: 'Government ID',
  selfie: 'Selfie',
  challengeCode: 'Challenge code',
  frames: 'Capture frames',
  rejectionNote: 'Rejection note',
  apiUnavailable: 'The API is unavailable. Please try again.',
  notAuthorized: 'You are not authorized to perform this action.',
  notPermitted: 'You are not permitted to view this section.',
  invalidCredentials: 'Invalid username or password.',
  unexpectedError: 'Something went wrong. Please try again.',
  required: 'This field is required.',
  invalidAmount: 'Enter a non-negative USDT amount with up to 6 decimals.',
  noRows: 'No records found.',
  loginRequired: 'Please log in to continue.',
  requestFailed: 'Request failed',
  validationFailed: 'Please correct the highlighted fields.',
  apiKeyCreateFailed: 'Unable to create the API key.',
  apiKeyRevokeFailed: 'Unable to revoke the API key.',
} as const;

export const statusLabels: Record<string, string> = {
  PENDING_APPROVAL: 'Pending approval',
  APPROVED: 'Approved',
  PROCESSING: 'Processing',
  COMPLETED: 'Completed',
  FAILED: 'Failed',
  REFUNDED: 'Refunded',
  REJECTED: 'Rejected',
};

export const transactionTypes = ['DEPOSIT', 'TRANSFER', 'ESCROW_HOLD', 'ESCROW_RELEASE', 'ESCROW_CANCEL', 'WITHDRAWAL', 'REFUND', 'FEE'] as const;
