export const labels = {
  appName: 'TrustMe Admin',
  login: 'Log in',
  logout: 'Log out',
  username: 'Username',
  password: 'Password',
  overview: 'Overview',
  settings: 'Settings',
  withdrawals: 'Withdrawals',
  ledger: 'Ledger',
  vaultUsdt: 'Vault USDT',
  couponsInCirculation: 'Coupons in circulation',
  feesCollected: 'Fees collected',
  withdrawalPending: 'Withdrawal pending',
  dust: 'Member dust',
  solvencySurplus: 'Solvency surplus',
  solvent: 'Solvent',
  insolvent: 'Insolvent',
  unavailable: 'unavailable',
  available: 'available',
  chain: 'Chain status',
  hotWallet: 'Hot wallet',
  headBlock: 'RPC head block',
  nextBlock: 'Next scan block',
  lag: 'Block lag',
  usdt: 'USDT',
  nativeBalance: 'Native balance (wei)',
  transactions24h: 'Transactions in the last 24 hours',
  transactionType: 'Transaction type',
  count: 'Count',
  withdrawalBaseFeeBps: 'Withdrawal base fee (bps)',
  minimumWithdrawalMicroUsdt: 'Minimum withdrawal (micro-USDT)',
  autoApprovalLimitMicroUsdt: 'Auto-approval limit (micro-USDT)',
  save: 'Save settings',
  barcode: 'Member barcode',
  grossCoupons: 'Gross coupons',
  fee: 'Fee',
  net: 'Net',
  destination: 'Destination',
  status: 'Status',
  chainTxHash: 'Chain transaction',
  createdAt: 'Created',
  broadcastedAt: 'Broadcasted',
  approve: 'Approve',
  reject: 'Reject',
  filter: 'Filter',
  allStatuses: 'All statuses',
  previous: 'Previous',
  next: 'Next',
  externalReference: 'External reference',
  coupons: 'Coupons',
  search: 'Search',
  from: 'From',
  to: 'To',
  entries: 'Entries',
  notPermitted: 'You are not permitted to view this section.',
  invalidCredentials: 'Invalid username or password.',
  unexpectedError: 'Something went wrong. Please try again.',
  required: 'This field is required.',
  noRows: 'No records found.',
  loginRequired: 'Please log in to continue.',
  requestFailed: 'Request failed',
} as const;

export const statusLabels: Record<string, string> = {
  PENDING_APPROVAL: 'Pending approval',
  APPROVED: 'Approved',
  PROCESSING: 'Processing',
  COMPLETED: 'Completed',
  FAILED: 'Failed',
  REFUNDED: 'Refunded',
  REJECTED: 'Rejected',
};
