import { StyleSheet } from 'react-native';

export const colors = {
  ink: '#16202A',
  muted: '#65727E',
  primary: '#176B87',
  background: '#F5F8FA',
  card: '#FFFFFF',
  border: '#D8E1E7',
  danger: '#B3261E',
  success: '#216E4E',
} as const;

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: colors.background, padding: 20 },
  centered: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: 24, backgroundColor: colors.background },
  scroll: { padding: 20, gap: 16 },
  title: { color: colors.ink, fontSize: 30, fontWeight: '700', textAlign: 'auto', writingDirection: 'auto' },
  heading: { color: colors.ink, fontSize: 24, fontWeight: '700', textAlign: 'auto', writingDirection: 'auto' },
  text: { color: colors.ink, fontSize: 18, textAlign: 'auto', writingDirection: 'auto', lineHeight: 28 },
  muted: { color: colors.muted, fontSize: 16, textAlign: 'auto', writingDirection: 'auto', lineHeight: 24 },
  demoLabel: { color: '#8A949C', fontSize: 13, textAlign: 'auto', writingDirection: 'auto', lineHeight: 18 },
  card: { backgroundColor: colors.card, borderRadius: 18, padding: 18, gap: 10, borderWidth: 1, borderColor: colors.border },
  input: { backgroundColor: colors.card, borderWidth: 1, borderColor: colors.border, borderRadius: 12, padding: 14, fontSize: 18, color: colors.ink, textAlign: 'auto', writingDirection: 'auto' },
  button: { backgroundColor: colors.primary, borderRadius: 12, padding: 15, alignItems: 'center' },
  buttonText: { color: '#FFFFFF', fontSize: 18, fontWeight: '700' },
  secondaryButton: { borderColor: colors.primary, borderWidth: 1, borderRadius: 12, padding: 14, alignItems: 'center' },
  buttonDisabled: { opacity: 0.45 },
  secondaryButtonText: { color: colors.primary, fontSize: 18, fontWeight: '700' },
  languageRow: { flexDirection: 'row', justifyContent: 'center', gap: 10 },
  languageButton: { borderColor: colors.border, borderWidth: 1, borderRadius: 12, padding: 10 },
  languageActive: { borderColor: colors.primary, borderWidth: 2, borderRadius: 12, padding: 9 },
  danger: { color: colors.danger, fontSize: 16, textAlign: 'auto', writingDirection: 'auto' },
  notice: { color: colors.success, fontSize: 16, textAlign: 'auto', writingDirection: 'auto' },
  row: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', gap: 10 },
  pill: { borderRadius: 99, backgroundColor: '#E5F2F5', paddingHorizontal: 10, paddingVertical: 5 },
  divider: { height: 1, backgroundColor: colors.border },
  socialAuthContainer: { gap: 12 },
  socialAuthRow: { flexDirection: 'row', gap: 12 },
  socialAuthButton: { flex: 1, height: 52, borderRadius: 12, alignItems: 'center', justifyContent: 'center', flexDirection: 'row', gap: 8, paddingHorizontal: 8 },
  socialAuthButtonBusy: { opacity: 0.5 },
  socialAuthGoogleButton: { backgroundColor: '#FFFFFF', borderColor: '#DADCE0', borderWidth: 1 },
  socialAuthGoogleText: { color: '#1F1F1F', fontSize: 16, fontWeight: '700' },
  socialAuthAppleButton: { backgroundColor: '#000000' },
  socialAuthAppleText: { color: '#FFFFFF', fontSize: 16, fontWeight: '700' },
});
