export const openapiDocument = {
  openapi: '3.0.3',
  info: { title: 'TrustMe Member API', version: '0.1.0' },
  components: {
    schemas: {
      ValidationError: {
        type: 'object',
        required: ['error', 'fields'],
        properties: {
          error: { type: 'string', example: 'validation failed' },
          fields: {
            type: 'array',
            items: {
              type: 'object',
              required: ['path', 'message'],
              properties: {
                path: { type: 'string', description: 'Dotted request field path' },
                message: { type: 'string' },
              },
            },
          },
        },
      },
    },
  },
  paths: {
    '/v1/auth/register': { post: { responses: { '201': { description: 'Registered member and tokens' }, '409': { description: 'Phone already registered' } } } },
    '/v1/auth/login': { post: { responses: { '200': { description: 'Member and tokens' }, '401': { description: 'Invalid phone or PIN' }, '423': { description: 'PIN temporarily locked' } } } },
    '/v1/auth/refresh': { post: { responses: { '200': { description: 'Rotated tokens' }, '401': { description: 'Unauthorized' } } } },
    '/v1/auth/pin-reset/request': { post: { responses: { '202': { description: 'Reset requested' }, '503': { description: 'Email delivery unavailable' } } } },
    '/v1/auth/pin-reset/confirm': { post: { responses: { '200': { description: 'Reset PIN and tokens' }, '401': { description: 'Invalid code' } } } },
    '/v1/me': {
      get: { responses: { '200': { description: 'Member profile, including identityVerification status and verifiedAt' }, '401': { description: 'Unauthorized' } } },
      patch: { responses: { '200': { description: 'Updated member profile' } } },
    },
    '/v1/me/identity': {
      get: { responses: { '200': { description: 'Country-aware identity policy and status' } } },
      post: {
        description: 'Check the authenticated member’s Iranian national ID against the mobile number stored on the account. Provider messages are not exposed.',
        requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['nationalCode'], properties: { nationalCode: { type: 'string', pattern: '^\\d{10}$' } } } } } },
        responses: {
          '200': { description: 'Identity verification result: VERIFIED, MISMATCH, or INCONCLUSIVE' },
          '400': { description: 'Invalid national code, missing phone number, or invalid Iranian mobile number' },
          '429': { description: 'Rate limit or identity-check cap reached' },
          '503': { description: 'Identity verification is not configured' },
        },
      },
    },
    '/v1/me/identity/live-capture-session': {
      post: {
        description: 'Create a five-minute server-issued live identity capture session with a shuffled frame order and challenge code.',
        responses: { '201': { description: 'Live capture session' }, '400': { description: 'Country is required' }, '409': { description: 'Manual path is unavailable, review is pending, or identity is verified' } },
      },
    },
    '/v1/me/identity/manual-review': {
      post: {
        description: 'Submit all four frames captured in a live identity session for manual review.',
        requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['captureSessionId'], properties: { captureSessionId: { type: 'string', format: 'uuid' } } } } } },
        responses: { '201': { description: 'Manual identity review submitted' }, '400': { description: 'Country or required capture frame is missing' }, '403': { description: 'Capture session or frame is not owned by the member' }, '409': { description: 'Manual review is unavailable, expired, already pending, or identity is verified' } },
      },
    },
    '/v1/me/disclosures': { get: { responses: { '200': { description: 'Pending balance disclosure requests for the member' } } } },
    '/v1/me/disclosures/{id}/deny': { post: { responses: { '204': { description: 'Disclosure request denied' }, '404': { description: 'Disclosure request not found' }, '409': { description: 'Disclosure request is no longer pending' } } } },
    '/v1/me/country': { put: { responses: { '200': { description: 'Updated account country' }, '409': { description: 'Country cannot change after verification' } } } },
    '/v1/me/barcodes': { get: { responses: { '200': { description: 'Member barcode search results' } } } },
    '/v1/me/barcodes/{barcodeId}': { get: { responses: { '200': { description: 'Member barcode details' }, '404': { description: 'Member not found' } } } },
    '/v1/me/pin': { post: { responses: { '204': { description: 'PIN changed' } } } },
    '/v1/me/email': { post: { responses: { '202': { description: 'Email verification requested' }, '503': { description: 'Email delivery unavailable' } } } },
    '/v1/me/email/verify': { post: { responses: { '200': { description: 'Verified member profile' } } } },
    '/v1/me/devices': { get: { responses: { '200': { description: 'Member devices' } } } },
    '/v1/me/devices/{id}': { delete: { responses: { '204': { description: 'Device revoked' }, '403': { description: 'Forbidden' } } } },
    '/v1/me/logout': { post: { responses: { '204': { description: 'Current device revoked' } } } },
    '/v1/me/balance': { get: { responses: { '200': { description: 'Member balance' } } } },
    '/v1/me/withdrawal-availability': { get: { responses: { '200': { description: 'Member withdrawal availability' } } } },
    '/v1/me/transactions': { get: { responses: { '200': { description: 'Member transaction history' } } } },
    '/v1/me/transfers': { post: { responses: { '201': { description: 'Transfer posted' } } } },
    '/v1/me/escrows': { post: { responses: { '201': { description: 'Escrow created' } } } },
    '/v1/me/escrows/{id}/release': { post: { responses: { '200': { description: 'Escrow released' }, '403': { description: 'Forbidden' } } } },
    '/v1/me/escrows/{id}/cancel': { post: { responses: { '200': { description: 'Escrow cancelled' }, '403': { description: 'Forbidden' } } } },
    '/v1/me/withdrawals': { post: { responses: { '201': { description: 'Withdrawal requested' } } } },
    '/v1/me/withdrawals/quote': { get: { responses: { '200': { description: 'Withdrawal fee quote' }, '400': { description: 'Withdrawal quote rejected' } } } },
    '/v1/me/contacts': {
      get: { responses: { '200': { description: 'Member contacts' } } },
      post: { responses: { '201': { description: 'Contact created' } } },
    },
    '/v1/me/contacts/{id}': {
      patch: { responses: { '200': { description: 'Contact updated' }, '403': { description: 'Forbidden' } } },
      delete: { responses: { '204': { description: 'Contact deleted' }, '403': { description: 'Forbidden' } } },
    },
    '/v1/me/loans': {
      get: { responses: { '200': { description: 'Member loans' } } },
      post: { responses: { '201': { description: 'Loan requested' } } },
    },
    '/v1/me/loans/{id}/repay': { post: { responses: { '200': { description: 'Loan repayment posted' }, '403': { description: 'Forbidden' } } } },
    '/v1/me/guarantees': { get: { responses: { '200': { description: 'Member guarantees' } } } },
    '/v1/me/guarantees/{id}/approve': { post: { responses: { '200': { description: 'Guarantee approved' }, '403': { description: 'Forbidden' } } } },
    '/v1/me/guarantees/{id}/activate': { post: { responses: { '200': { description: 'Guarantee activated' }, '403': { description: 'Forbidden' } } } },
    '/v1/me/guarantees/{id}/decline': { post: { responses: { '200': { description: 'Guarantee declined' }, '403': { description: 'Forbidden' } } } },
    '/v1/me/media': { post: { responses: { '201': { description: 'Media uploaded' }, '413': { description: 'Media too large' }, '415': { description: 'Unsupported media type' } } } },
    '/v1/me/media/{id}': { get: { responses: { '200': { description: 'Media download' }, '404': { description: 'Not found' } } } },
    '/v1/me/refunds': {
      get: { responses: { '200': { description: 'Refund requests' } } },
      post: { responses: { '201': { description: 'Refund request created' }, '409': { description: 'Pending refund exists' } } },
    },
    '/v1/me/refunds/{id}': {
      get: { responses: { '200': { description: 'Refund detail' }, '404': { description: 'Not found' } } },
    },
    '/v1/me/refunds/{id}/approve': { post: { responses: { '200': { description: 'Refund approved' }, '409': { description: 'Refund unavailable' } } } },
    '/v1/me/refunds/{id}/reject': { post: { responses: { '200': { description: 'Refund rejected' } } } },
    '/v1/me/charities': { get: { responses: { '200': { description: 'Active charities' } } } },
    '/v1/me/charities/{id}/donations': { post: { responses: { '201': { description: 'Donation posted' } } } },
    '/v1/me/aid-requests': {
      get: { responses: { '200': { description: 'Applicant aid requests' } } },
      post: { responses: { '201': { description: 'Aid request created' } } },
    },
    '/v1/me/aid-requests/{id}/documents': { post: { responses: { '200': { description: 'Aid documents attached' } } } },
    '/v1/me/charity-requests': { get: { responses: { '200': { description: 'Charity requests' } } } },
    '/v1/me/charity-requests/{id}/approve': { post: { responses: { '200': { description: 'Aid approved' }, '409': { description: 'Insufficient charity balance' } } } },
    '/v1/me/charity-requests/{id}/reject': { post: { responses: { '200': { description: 'Aid rejected' } } } },
    '/v1/me/charity-requests/{id}/request-documents': { post: { responses: { '200': { description: 'Documents requested' } } } },
    '/v1/users': { post: { responses: { '201': { description: 'Created' }, '401': { description: 'Unauthorized' } } } },
    '/v1/users/{barcodeId}/balance': { get: { responses: { '200': { description: 'Balance' } } } },
    '/v1/transfers': { post: { responses: { '201': { description: 'Transfer posted' } } } },
    '/v1/escrows': { post: { responses: { '201': { description: 'Escrow created' } } } },
    '/v1/escrows/{id}/release': { post: { responses: { '200': { description: 'Escrow released' } } } },
    '/v1/escrows/{id}/cancel': { post: { responses: { '200': { description: 'Escrow cancelled' } } } },
    '/v1/withdrawals': { post: { responses: { '201': { description: 'Withdrawal requested' } } } },
    '/v1/withdrawals/availability': { get: { responses: { '200': { description: 'Withdrawal availability and blockers' } } } },
    '/v1/public/reserves': { get: { responses: { '200': { description: 'Public real and demo reserve figures' } } } },
    '/v1/public/ledger': { get: { responses: { '200': { description: 'Anonymized completed public ledger feed' } } } },
    '/v1/public/barcodes/{barcodeId}': { get: { responses: { '200': { description: 'Public barcode status only' }, '404': { description: 'Member not found' } } } },
    '/v1/public/barcodes/{barcodeId}/disclosure': { post: { responses: { '201': { description: 'Created one-time disclosure request' }, '409': { description: 'Disclosure request already pending' } } } },
    '/v1/public/disclosures/{requestId}/confirm': { post: { responses: { '200': { description: 'One-time approved balance disclosure' }, '401': { description: 'Invalid disclosure code' }, '410': { description: 'Disclosure request expired or already consumed' } } } },
    '/v1/withdrawals/{id}': { get: { responses: { '200': { description: 'Withdrawal status' } } } },
    '/v1/loans': {
      get: { responses: { '200': { description: 'Member loans' } } },
      post: { responses: { '201': { description: 'Loan requested' } } },
    },
    '/v1/loans/{id}/disburse': { post: { responses: { '200': { description: 'Loan disbursed' } } } },
    '/v1/loans/{id}/repay': { post: { responses: { '200': { description: 'Loan repayment posted' } } } },
    '/v1/loans/{id}/claim': { post: { responses: { '200': { description: 'Guarantees claimed' } } } },
    '/v1/guarantees': { get: { responses: { '200': { description: 'Member guarantees' } } } },
    '/v1/guarantees/{id}/approve': { post: { responses: { '200': { description: 'Guarantee approved and locked' } } } },
    '/v1/guarantees/{id}/activate': { post: { responses: { '200': { description: 'Guarantee activated' } } } },
    '/v1/guarantees/{id}/cancel': { post: { responses: { '200': { description: 'Guarantee cancelled' } } } },
    '/v1/guarantees/{id}/decline': { post: { responses: { '200': { description: 'Guarantee declined' } } } },
    '/admin/login': {
      post: {
        requestBody: {
          required: true,
          content: {
            'application/json': {
              schema: {
                type: 'object',
                required: ['username', 'password'],
                properties: {
                  username: { type: 'string', description: 'Admin username' },
                  password: { type: 'string', format: 'password' },
                },
              },
            },
          },
        },
        responses: { '200': { description: 'Admin JWT' }, '401': { description: 'Invalid credentials' } },
      },
    },
    '/admin/overview': { get: { responses: { '200': { description: 'Admin overview' } } } },
    '/admin/settings': {
      get: { responses: { '200': { description: 'Admin settings' } } },
      patch: { responses: { '200': { description: 'Updated admin settings' } } },
    },
    '/admin/withdrawals': { get: { responses: { '200': { description: 'Admin withdrawal queue' } } } },
    '/admin/withdrawals/{id}/approve': { post: { responses: { '200': { description: 'Withdrawal approved' } } } },
    '/admin/withdrawals/{id}/reject': { post: { responses: { '200': { description: 'Withdrawal rejected' } } } },
    '/admin/identity-reviews': { get: { responses: { '200': { description: 'Admin identity review queue' }, '403': { description: 'Reviewer role required' } } } },
    '/admin/identity-reviews/{id}/media/{assetId}': { get: { responses: { '200': { description: 'Protected identity-review media' }, '403': { description: 'Reviewer role required' }, '404': { description: 'Media not found or no longer attached' } } } },
    '/admin/identity-reviews/{id}/approve': { post: { responses: { '200': { description: 'Identity review approved' }, '409': { description: 'Review is no longer pending or manual path is unavailable' } } } },
    '/admin/identity-reviews/{id}/reject': { post: { responses: { '200': { description: 'Identity review rejected' }, '409': { description: 'Review is no longer pending' } } } },
    '/admin/ledger': { get: { responses: { '200': { description: 'Admin ledger entries' } } } },
    '/admin/charities': { post: { responses: { '201': { description: 'Charity created' } } } },
    '/admin/charities/{id}': { patch: { responses: { '200': { description: 'Charity updated' } } } },
    '/admin/charities/{id}/agents': { post: { responses: { '201': { description: 'Charity agent added' } } } },
    '/admin/charities/{id}/agents/{userId}': { delete: { responses: { '200': { description: 'Charity agent revoked' } } } },
  },
} as const;
