import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import solc from 'solc';

async function main() {
const root = path.resolve(new URL('..', import.meta.url).pathname);
const sourcePath = path.join(root, 'contracts', 'TrustCouponEscrow.sol');
const outputPath = path.join(root, 'packages', 'core', 'src', 'escrow-abi.ts');
const source = await readFile(sourcePath, 'utf8');
const output = JSON.parse(solc.compile(JSON.stringify({
  language: 'Solidity',
  sources: { 'TrustCouponEscrow.sol': { content: source } },
  settings: { optimizer: { enabled: true, runs: 200 }, outputSelection: { '*': { '*': ['abi', 'evm.bytecode.object'] } } },
}))) as {
  errors?: Array<{ severity: string; formattedMessage: string }>;
  contracts: Record<string, Record<string, { abi: unknown; evm: { bytecode: { object: string } } }>>;
};
const errors = output.errors ?? [];
const fatal = errors.filter((error) => error.severity === 'error');
if (fatal.length > 0) throw new Error(fatal.map((error) => error.formattedMessage).join('\n'));
const contract = output.contracts['TrustCouponEscrow.sol']?.TrustCouponEscrow;
if (contract === undefined || contract.evm.bytecode.object === '') throw new Error('TrustCouponEscrow compilation produced no bytecode');
const contents = `// Generated by scripts/compile-escrow.ts. Do not edit by hand.
export const trustCouponEscrowAbi = ${JSON.stringify(contract.abi, null, 2)} as const;
export const trustCouponEscrowBytecode = '0x${contract.evm.bytecode.object}';
`;
await writeFile(outputPath, contents, 'utf8');
process.stdout.write(`compiled TrustCouponEscrow to ${path.relative(root, outputPath)}\n`);
}

void main();
