#!/usr/bin/env bash
# The TrustMe-only port map. Keep this file in sync with DEPLOYMENT.md.
if [[ -z "${TRUSTME_PORTS_LOADED:-}" ]]; then
  readonly TRUSTME_EXPECTED_PG_PORT=5434
  readonly TRUSTME_EXPECTED_REPLICATION_TUNNEL_PORT=5435
  readonly TRUSTME_EXPECTED_REDIS_PORT=6380
  readonly TRUSTME_EXPECTED_API_PORT=3121
  readonly TRUSTME_EXPECTED_ADMIN_PORT=3122
  readonly TRUSTME_EXPECTED_FAILBACK_TUNNEL_PORT=5436
  readonly TRUSTME_PORTS_LOADED=1
fi
: "$TRUSTME_EXPECTED_PG_PORT" "$TRUSTME_EXPECTED_REPLICATION_TUNNEL_PORT"
: "$TRUSTME_EXPECTED_REDIS_PORT" "$TRUSTME_EXPECTED_API_PORT"
: "$TRUSTME_EXPECTED_ADMIN_PORT" "$TRUSTME_EXPECTED_FAILBACK_TUNNEL_PORT"
